import { useState } from "react";
import Link from "next/link";
import Head from "next/head";

export const HeadWrapper = () => {
  return (
    <Head>
      <title>JayB Space</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export const Header = () => {
  const [navbar, setNavbar] = useState(false);
  return (
    <nav className="w-full bg-gray-200">
      <div className="justify-between px-4 mx-auto lg:max-w-7xl md:items-center md:flex md:px-8">
        <div>
          <div className="flex items-center justify-between py-3 md:py-5 md:block">
            <Link
              href="/"
              className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="currentColor"
                viewBox="0 0 64 64"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="w-10 h-10 iconify iconify--emojione-monotone"
              >
                <path d="M32 2C15.432 2 2 15.432 2 32s13.432 30 30 30s30-13.432 30-30S48.568 2 32 2m9.095 35.334c0 2.469-.417 4.424-1.251 5.867c-1.412 2.441-3.959 3.662-7.642 3.662s-6.153-.988-7.411-2.963c-1.256-1.975-1.885-4.67-1.885-8.082v-.668h5.729v.668c.049 2.244.279 3.822.693 4.734c.412.912 1.297 1.369 2.652 1.369c1.344 0 2.231-.498 2.663-1.496c.259-.592.388-1.588.388-2.992V17.139h6.063v20.195z" />
              </svg>
              <span className="ml-3 text-xl">JayB</span>
            </Link>

            <div className="md:hidden">
              <button
                className="p-2 text-gray-700 rounded-md outline-none focus:border-gray-400 focus:border"
                onClick={() => setNavbar(!navbar)}
              >
                {navbar ? (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-6 h-6 text-gray-800"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fillRule="evenodd"
                      d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                      clipRule="evenodd"
                    />
                  </svg>
                ) : (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-6 h-6 text-gray-800"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M4 6h16M4 12h16M4 18h16"
                    />
                  </svg>
                )}
              </button>
            </div>
          </div>
        </div>
        <div>
          <div
            className={`flex-1 justify-self-center pb-3 mt-8 md:block md:pb-0 md:mt-0 ${
              navbar ? "block" : "hidden"
            }`}
          >
            <ul className="items-center justify-center space-y-8 md:flex md:space-x-6 md:space-y-0">
              <li className="hover:text-gray-900">
                <Link href="/">Home</Link>
              </li>
              <li className="hover:text-gray-900">
                <Link href="/blogs">Blogs</Link>
              </li>
              <li className="hover:text-gray-900">
                <Link href="/portfolios">Portfolios</Link>
              </li>
              <li className="hover:text-gray-900">
                <Link href="/contact">Contact</Link>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  );
};
